package br.com.smart4.gestaoagriculturaapi.api.domains;

public enum StreetType {
	RUA, AVENIDA, LOTE, TRAVESSA, ALAMEDA, BECO, QUADRA, PARQUE, VILA, POVOADO, CONDOMINIO, FAZENDA, ESTRADA, SITIO,
	FAVELA, JARDIM, ESPLANADA, CAMPO, BR, CAMINHO, CONDOMÍNIO, ENTROCAMENTO, LOCALIDADE, PRAÇA, RODOVIA, SÍTIO,
	DISTRITO, LOTEAMENTO, REGIÃO, BAIA, LARGO, VEREDA, LADEIRA, PRAIA, ALDEIA, CONJUNTO, CHACARA, VIADUTO, ELEVADA,
	TREVO, RÓTULA, USINA, ESTANCIA, VIA, DESVIO, SUBIDA, RAMAL, MARGEM, RAMPA, CANAL, ASSENTAMENTO, VIELA
}
