spring:
  application:
    name: ${SPRING_APPLICATION_NAME:gestaoagriculturaapi}

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/smartagrodb?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:16MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:16MB}

server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/gestaoagriculturaapi}

app:
  version: ${APP_VERSION:1.0.0}
  apiKey: ${API_KEY:AIzaSyB4hsbTQ9Vsb_2YkIdzJCnjYlM4-IN5Fbo}
  jwtSecret: ${APP_JWT_SECRET:b@dm%#2VA3YN??=cO_onfb$*HYzZr)0"T77nnmI$'#uL=55yIx2[5qbOwlRDJHhLz-bAYB1pnP5qNKJb9qU8[g%#OrXm'ZhecuD10P"mwNPyVyEiFKJPz)}
  jwtExpirationInMs: ${APP_JWT_EXPIRATION:3600000}

management:
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}

info:
  app:
    name: ${INFO_APP_NAME:@project.name@}
    version: ${INFO_APP_VERSION:@project.version@}

# Uncomment and configure if using Spring Boot Admin
# spring:
#   boot:
#     admin:
#       client:
#         url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:8081}
